---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: local-pv-1
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/k8s-local-pv/local-pv-1
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: local-pv-2
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/k8s-local-pv/local-pv-2
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual