kind: Pod
apiVersion: v1
metadata:
  name: local-pv-pod
  labels:
    app: pvtest
spec:
  containers:
    - name: busybox
      image: busybox
      volumeMounts:
        - mountPath: "/local-data"
          name: local-volume
  volumes:
    - name: local-volume
      persistentVolumeClaim:
       claimName: local-pvc-1