apiVersion: v1
kind: Service
metadata:
  name: dns-svc2
  labels:
    app: dns-app2
spec:
  clusterIP: None
  selector:
    app: dns-app2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: dns-cass2
spec:
  serviceName: "dns-svc2"
  replicas: 2
  template:
    metadata:
      labels:
        app: dns-app2
    spec:
      containers:
        - name: app2
          image: reg.spp.com/spp/cass-dev:v1.2.19
