apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: default
  annotations:
    # https://github.com/kubernetes/examples/issues/89
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: cassandra
spec:
  ports:
    - port: 80
      name: cassandra
  selector:
    cluster: nginx
