kind: Pod
apiVersion: v1
metadata:
  name: aws-ebs-pod
spec:
  volumes:
    - name: mysql-data-volume
      persistentVolumeClaim:
       claimName: aws-ebs-pvc
  containers:
    - name: mysql-container
      image: mysql
      ports:
        - containerPort: 3306
          name: "mysql-server"
      volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-data-volume