---
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql-cluster-with-volume
  namespace: mysql-cluster
spec:
  members: 1
  rootPasswordSecret:
    name: mysql-root-user-secret
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
#  backupVolumeClaimTemplate:
#    metadata:
#      name: backup-data
#    spec:
#      storageClassName: manual
#      accessModes:
#        - ReadWriteMany
#      resources:
#        requests:
#          storage: 1Gi
