apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-operator-config
  namespace: mysql-cluster
  labels:
    app: mysql-operator
data:
  mysql-operator-config.yaml: |
    images:
      mysqlServer: reg.spp.com/spp/mysql-server:8.0.12
      mysqlAgent: reg.spp.com/spp/mysql-agent:0.3.0
