apiVersion: v1
kind: Pod
metadata:
  name: cass-pod-3
  labels:
    app: cass
spec:
  containers:
  - name: cass-container
    image: reg.spp.com/spp/cass-dev:v1.2.18
    args: ['cassandra','-f']
    env:
    - name: CASSANDRA_SEEDS
      value: "172.30.88.15"
    - name: CASSANDRA_INITIAL_TOKEN
      value: "232000"
